server:
  port: 8080
  error:
    include-stacktrace: never
    include-binding-errors: never

spring:
  application:
    name: react-productos-crud-server
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/${sid}
    username: ${bd_username}
    password: ${bd_password}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      

carpeta: 'c:/producto/imagenes/'
      
